# Generated by Django 5.2.5 on 2026-01-13 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('SOCIAL', 'Social Media'), ('REFERRAL', 'Referral'), ('IN_PERSON', 'In Person'), ('EMAIL', 'Email'), ('CALL', 'Phone Call'), ('OTHER', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONVERTED', 'Converted'), ('FORWARDED', 'Forwarded'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('SHOPPING_MALL', 'Shopping Mall'), ('HOUSING', 'Housing Scheme'), ('COMMERCIAL', 'Commercial Project')], max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('launch_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LAUNCHED', 'Launched'), ('COMPLETED', 'Completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Manager', max_length=50)),
                ('emp_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('SHOP', 'Shop'), ('1BED', '1 Bed Apartment'), ('2BED', '2 Bed Apartment'), ('3BED', '3 Bed Apartment'), ('4BED', '4 Bed Apartment'), ('OFFICE', 'Office')], max_length=20)),
                ('total_units', models.PositiveIntegerField()),
                ('floor', models.CharField(choices=[('BASEMENT', 'Basement'), ('GROUND', 'Ground Floor'), ('1', '1st Floor'), ('2', '2nd Floor'), ('3', '3rd Floor'), ('OTHER', 'Other')], max_length=20)),
                ('area_size', models.FloatField(help_text='Area in sq ft')),
                ('rate_per_sqft', models.FloatField()),
                ('commission_percent', models.FloatField()),
                ('price', models.FloatField(editable=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='gm.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sale_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment')], max_length=20)),
                ('payment_stage', models.CharField(choices=[('DOWN', 'Down Payment'), ('PARTIAL', 'Partial Payment'), ('FULL', 'Full Payment'), ('INSTALLMENT', 'Installment'), ('OTHER', 'Other')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('converted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_converted', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.lead')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gm.project')),
                ('project_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gm.projectunit')),
                ('supervised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_supervised', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
