# Generated by Django 5.2.5 on 2026-01-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('schedule_type', models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special')], max_length=20)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attendance_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('record_count', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('father_name', models.CharField(blank=True, max_length=120, null=True)),
                ('cnic_no', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_id', models.CharField(max_length=30, unique=True)),
                ('designation', models.CharField(choices=[('Advisor to CEO', 'Advisor to CEO'), ('Assistant', 'Assistant'), ('BDE', 'BDE'), ('Cameraman', 'Cameraman'), ('Cleaner', 'Cleaner'), ('Cook Assistant', 'Cook Assistant'), ('Digital Marketing', 'Digital Marketing'), ('Finance Manager', 'Finance Manager'), ('GM', 'GM'), ('Graphic Designer', 'Graphic Designer'), ('Manager', 'Manager'), ('HR Assistant', 'HR Assistant'), ('HR Officer', 'HR Officer'), ('Manager Office Boy', 'Manager Office Boy'), ('Operation Manager', 'Operation Manager'), ('Project Manager', 'Project Manager'), ('S&M Manager', 'S&M Manager'), ('Sales Executive', 'Sales Executive'), ('Team Leader', 'Team Leader')], max_length=50)),
                ('department', models.CharField(choices=[('Accounts', 'Accounts'), ('Finance', 'Finance'), ('HR', 'HR'), ('Kitchen', 'Kitchen'), ('Lower Management', 'Lower Management'), ('Marketing', 'Marketing'), ('Media & PR', 'Media & PR'), ('Operations', 'Operations'), ('Sales', 'Sales'), ('Sales & Marketing', 'Sales & Marketing')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('old_emp_id', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employees/profile/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Short Leave', 'Short Leave'), ('Full Leave', 'Full Leave'), ('On Duty', 'On Duty')], max_length=20)),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Accounts', 'Accounts'), ('Finance', 'Finance'), ('HR', 'HR'), ('Kitchen', 'Kitchen'), ('Lower Management', 'Lower Management'), ('Marketing', 'Marketing'), ('Media & PR', 'Media & PR'), ('Operations', 'Operations'), ('Sales', 'Sales'), ('Sales & Marketing', 'Sales & Marketing')], editable=False, max_length=50)),
                ('designation', models.CharField(choices=[('Advisor to CEO', 'Advisor to CEO'), ('Assistant', 'Assistant'), ('BDE', 'BDE'), ('Cameraman', 'Cameraman'), ('Cleaner', 'Cleaner'), ('Cook Assistant', 'Cook Assistant'), ('Digital Marketing', 'Digital Marketing'), ('Finance Manager', 'Finance Manager'), ('GM', 'GM'), ('Graphic Designer', 'Graphic Designer'), ('Manager', 'Manager'), ('HR Assistant', 'HR Assistant'), ('HR Officer', 'HR Officer'), ('Manager Office Boy', 'Manager Office Boy'), ('Operation Manager', 'Operation Manager'), ('Project Manager', 'Project Manager'), ('S&M Manager', 'S&M Manager'), ('Sales Executive', 'Sales Executive'), ('Team Leader', 'Team Leader')], editable=False, max_length=50)),
                ('date', models.DateField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Full Leave', 'Full Leave'), ('Short Leave', 'Short Leave'), ('On Duty', 'On Duty')], default='Present', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
