# Generated by Django 5.2.5 on 2026-01-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceupload',
            name='record_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
