# Generated by Django 5.2.5 on 2026-01-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_attendanceupload_record_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
